celebrities = {
    "Channing Tatum": 1,
    "Christina Applegate": 2,
    "Richard E. Grant": 3,
    "S. Epatha Merkerson": 4,
    "Farah Fath": 5,
    "Jim Beaver": 6,
    "Cheryl Hines": 7,
    "Michael Vartan": 8,
    "Hayden Christensen": 9,
    "Laurence Fishburne": 10,
    "KathrinJ oosten": 11,
    "Patrick Warburton": 12,
    "Jamie Lee Curtis": 13,
    "Jason Judeikis": 14,
    "Billy Burke": 15,
    "Robert Pattinson": 16,
    "Melissa Egan": 17,
    "Morena Baccarin": 18,
    "Jolene Blalock": 19,
    "Matthew Lillard": 20,
    "Alicia Goranson": 21,
    "Jennie Garth": 22,
    "Wanda De Jesus": 23,
    "Tracey Bregman": 24,
    "Tracey Gold": 25,
    "Brendan Fraser": 26,
    "Kellan Lutz": 27,
    "John Travolta": 28,
    "Pierce Brosnan": 29,
    "Jasmine Guy": 30,
    "Swoosie Kurtz": 31,
    "Diego Luna": 32,
    "Danny Glover": 33,
    "David Cross": 34,
    "Farrah Fawcet": 35,
    "Paul Walker": 36,
    "Matt Long": 37,
    "Andy García": 38,
    "Casey Affleck": 39,
    "Carla Gallo": 40,
    "James Brolin": 41,
    "Christian Bale": 42,
    "Nadia Bjorlin": 43,
    "Valerie Bertinelli": 44,
    "Alec Baldwin": 45,
    "Tamara Braun": 46,
    "Andy Serkis": 47,
    "Jackson Rathbone": 48,
    "Robert Redford": 49,
    "Julie Marie Berman": 50,
    "Chris Kattan": 51,
    "Benicio del Toro": 52,
    "Anthony Hopkins": 53,
    "Leah Michele": 54,
    "Jean-Claude Van Damme": 55,
    "Adrienne Frantz": 56,
    "Kim Fields": 57,
    "Wendie Malick": 58,
    "Lacey Chabert": 59,
    "Harry Connick Jr.": 60,
    "Cam Gigandet": 61,
    "Andrea Anders": 62,
    "Chris Noth": 63,
    "Cary Elwes": 64,
    "Aisha Hinds": 65,
    "Chris Rock": 66,
    "Neve Campbell": 67,
    "Susan Dey": 68,
    "Robert Duvall": 69,
    "Caroline Dhavernas": 70,
    "Marilu Henner": 71,
    "Christian Slater": 72,
    "Kris Kristofferson": 73,
    "Shelley Long": 74,
    "Alan Arkin": 75,
    "Faith Ford": 76,
    "Jason Bateman": 77,
    "Edi Gathegi": 78,
    "Emile Hirsch": 79,
    "Joaquin Phoenix": 80
}
